dist: bionic
sudo: required
language: minimal
env:
  global:
    - IMAGE_NAME=""
    - S6_VERSION="2.0.0.1"
    - DOCKER_CLI_EXPERIMENTAL="enabled"
before_install:
  - sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add 
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  - sudo apt update
  - sudo apt install -y docker-ce
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
install:
  - docker buildx create --use --name xbuild
  - docker buildx inspect --bootstrap
script: bash build.sh